### PR TITLE
Add Spring, spring-watcher-listen, and Listen

### PR DESCRIPTION
**Pull request by nimmolo**
Another development-only tool that i'm finding helpful. 

[Spring](https://github.com/rails/spring) is a Rails-maintained application preloader. _"It speeds up development by keeping your application running in the background, so you don't need to boot it every time you run a test, rake task or migration."_

[Listen](https://github.com/guard/listen) allows Spring to [work more efficiently](https://github.com/rails/spring#watching-files-and-directories) by sending it notifications of directory changes. It can also be used independently, but this PR does not implement it outside of Spring.

[spring-watcher-listen](https://github.com/rails/spring-watcher-listen/pull/26) connects the two.

Versions of all three locked to work with Rails 5.2 and each other.

Spring (v4) is, bundled and active by default in Rails 6 (this PR is for Spring v3, the last version that works with Rails 5). It's back to inactive by default in Rails 7 (because "computers are faster" they say), but it's still bundled with Rails 7 currently. 

If anyone objects for any reason, no problem. I'm open to using it local-only.

### CODE REVIEW

**Comment by JoeCohen** [comment]
I'd love it to have some time shaved off test runs. But I'm seeing some issues:
1. Will this configuration run on the M1? (Nathan has an M1.)
See https://github.com/rails/spring/issues/635 (suggesting upgrading to `listen >= 3.3.0`; but our Gemfile says `gem "listen", ">= 3.0.5", "< 3.2`)
2. Should the following change be made in config/environments/test.rb: 
config.cache_classes = ~~true~~ false   
See https://github.com/rails/spring#enable-reloading
3. I think it's not working for me. In particular: after a test run spring is not running:
```ruby
vagrant@ubuntu-focal /vagrant/mushroom-observer (nimmo-add-spring-listen)
$ grep "config.cache_classes" config/environments/test.rb
  # config.cache_classes = true
  config.cache_classes = false
vagrant@ubuntu-focal /vagrant/mushroom-observer (nimmo-add-spring-listen)
vagrant@ubuntu-focal /vagrant/mushroom-observer (nimmo-add-spring-listen)
$ rails t
...
vagrant@ubuntu-focal /vagrant/mushroom-observer (nimmo-add-spring-listen)
$ spring status
Spring is not running.
```
Compare to https://github.com/rails/spring#usage. (I'll try to see if I'm doing something wrong.)

4. When I start a test run, I get the following warnings. I don't understand their significance. (And maybe they're related to the fact that Spring isn't running after the tests.):
```ruby
vagrant@ubuntu-focal /vagrant/mushroom-observer (nimmo-add-spring-listen)
$ rails t
/vagrant/mushroom-observer/app/classes/map_collapsible.rb:49: warning: already initialized constant CollapsibleCollectionOfMappableObjects::PRECISION
/vagrant/mushroom-observer/app/classes/map_collapsible.rb:49: warning: previous definition of PRECISION was here
/vagrant/mushroom-observer/app/classes/map_collapsible.rb:70: warning: already initialized constant CollapsibleCollectionOfMappableObjects::MAX_PRECISION
/vagrant/mushroom-observer/app/classes/map_collapsible.rb:70: warning: previous definition of MAX_PRECISION was here
/vagrant/mushroom-observer/app/classes/map_collapsible.rb:71: warning: already initialized constant CollapsibleCollectionOfMappableObjects::MIN_PRECISION
/vagrant/mushroom-observer/app/classes/map_collapsible.rb:71: warning: previous definition of MIN_PRECISION was here
Started with run options --seed 40014
```

**Comment by pellaea** [comment]
The MIN_MAX_PRECISION are constants I probably added incorrectly to the map
stuff.  I bet there's a better way of doing it.  So you can probably add
that to the "uncovering hidden bugs" column.

**Comment by mo-nathan** [comment]
I've merged this into the mo-docker branch and everything seems to be working.  Like Joe, I see not speed improvements running the tests, but I also see no downside.  I'm fine merging it into master.

**Comment by JoeCohen** [comment]
@mo-nathan: Can you run tests in the mo-docker branch?

**Comment by JoeCohen** [comment]
That was a dumb question. You said you were running them.

**Comment by JoeCohen** [comment]
More important question:
When you run the tests, are you getting the "already initialized constant" warnings? See https://github.com/MushroomObserver/mushroom-observer/pull/824#issuecomment-1015891117
If so, what if anything, should we do about that before merging?
I just switched to master, and am getting the same warnings there.

**Comment by JoeCohen** [comment]
It's just me; the "already initialized constant" warnings are just on my desktop, not on my laptop.

**Comment by JoeCohen** [comment]
In order to fix this, I had to rebuild my vm, starting from cloning the repo. 
Perhaps my problem was due to my following the directions to "springify executables". https://github.com/rails/spring#setup
I'll double-check that tomorrow if I have time.
But right now I'll merge this.

**Comment by JoeCohen** [comment]
Using Spring in test environment
1. The "already initialized constant" warnings were due to my changing  `config.cache_classes` to false in  config/environments/test.rb. You have to do that in order to run Spring in that environment. https://github.com/rails/spring#enable-reloading
2. I won't be using Spring for the tests. Although Spring did improve "user" and "sys" times, it didn't change "real" time.

Without Spring:
```
$ time rails t
...
Finished in 198.49247s
...
real	3m24.552s
user	2m9.653s
sys	0m42.491s
```
With Spring:
```

$ time spring rails t
Running via Spring preloader in process 15117
...
Finished in 195.71937s
real	3m19.578s
user	0m0.251s
sys	0m0.028s

$ time spring rails t
Running via Spring preloader in process 20955
...
Finished in 212.87733s
...
real	3m36.885s
user	0m0.245s
sys	0m0.037s
```

**Comment by nimmolo** [comment]
Hi Joe - sorry to take awhile to get back to these questions, I couldn't remember how i had it set up.  I realize it's merged...

Did you set it up to use the `bin/` prefix before the `rails` or `rake` command, or did you [set up an](https://github.com/rails/spring#setup) `.envrc` file?

**Comment by JoeCohen** [comment]
Neither.
I manually modified config/environments/test.rb. 
Then ran `time spring rails t`.
